
version: '3'

services:
  password_generator:
    build: ./app
    container_name: password_generator
    restart: always
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./app:/app
    networks:
      - network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - password_generator
    networks:
      - network

networks:
  network:
    driver: bridge
